from pathlib import Path
import re


social = [
# Platforms
("Facebook","Facebook is a social networking platform where people and organizations can create profiles, connect with others, publish posts, share photos and videos, join groups, follow pages, and communicate through messaging."),
("Instagram","Instagram is a visual social media platform focused on photos, short-form videos, Stories, Reels, direct messaging, creator profiles, and discovery through feeds, search, and recommendations."),
("YouTube","YouTube is a video-sharing platform where users and organizations can upload, watch, stream, comment on, and share video content. It supports channels, subscriptions, playlists, Shorts, live streams, memberships, and advertising."),
("WhatsApp","WhatsApp is a messaging platform supporting individual and group chats, voice calls, video calls, media sharing, status updates, communities, and business communication."),
("Messenger","Facebook Messenger is a messaging service for text conversations, group chats, voice calls, video calls, media sharing, and interactions between people and businesses."),
("TikTok","TikTok is a short-form video platform centered on vertical video, music, effects, recommendations, creator profiles, comments, direct messages, live streams, and algorithmic discovery."),
("X","X is a social platform for public posts, conversations, media sharing, direct messages, communities, live content, and real-time discussion around news, entertainment, technology, sports, and other topics."),
("LinkedIn","LinkedIn is a professional networking platform used for professional profiles, recruiting, company pages, job searches, industry discussions, articles, newsletters, and business networking."),
("Reddit","Reddit is a community discussion platform organized into topic-focused communities called subreddits. Users can submit posts and comments, vote on content, and participate in discussions."),
("Pinterest","Pinterest is a visual discovery and bookmarking platform where users save content as Pins and organize them into boards. It is widely used for ideas related to fashion, food, design, travel, shopping, and hobbies."),
("Snapchat","Snapchat is a multimedia messaging and social platform known for disappearing messages, Stories, camera effects, lenses, short videos, and visual communication."),
("Telegram","Telegram is a cloud-based messaging platform supporting individual chats, large groups, channels, media sharing, bots, voice and video communication, and communities."),
("Discord","Discord is a communication platform organized around servers and channels. It supports text chat, voice, video, screen sharing, roles, moderation tools, bots, and communities."),
("Threads","Threads is a text-focused social platform associated with Instagram. It supports posts, replies, profiles, conversations, media sharing, and discovery of public discussions."),
("Twitch","Twitch is a live-streaming platform strongly associated with gaming but also used for music, creative work, conversations, education, and other live content."),
("Mastodon","Mastodon is a decentralized social networking platform based on ActivityPub. Independent servers, called instances, can communicate with one another while maintaining their own moderation and community rules."),
("Bluesky","Bluesky is a social networking platform built around an open social networking protocol called AT Protocol. It supports public posts, profiles, feeds, replies, follows, and customizable discovery."),
("Tumblr","Tumblr is a blogging and social platform that combines short-form publishing with following, reblogging, multimedia posts, tags, and community interaction."),
("Quora","Quora is a question-and-answer platform where users ask questions, write answers, follow topics, and interact through voting and discussion."),
("Medium","Medium is an online publishing platform where writers and organizations publish articles and readers discover, follow, and recommend written content."),
("WeChat","WeChat is a multifunctional Chinese messaging and social platform that combines chats, groups, social feeds, payments, mini programs, and other services."),
("Weibo","Sina Weibo is a Chinese social media platform centered on short posts, hashtags, media, public accounts, trending topics, and real-time discussion."),
("VK","VK is a social networking platform popular in Russian-speaking communities. It supports profiles, communities, messaging, media sharing, music, video, and social discovery."),
("LINE","LINE is a messaging and social platform widely used in Japan and several Asian markets. It supports chats, calls, stickers, official accounts, communities, and digital services."),
("KakaoTalk","KakaoTalk is a South Korean messaging platform supporting individual and group chats, calls, multimedia, channels, stickers, and integration with other Kakao services."),
("Signal","Signal is a privacy-focused messaging application that provides end-to-end encrypted messaging and calling. It emphasizes privacy, minimal data collection, and open-source security technology."),
("Skype","Skype is a communication service supporting instant messaging, voice calls, video calls, screen sharing, and other collaboration features."),
("Viber","Viber is a messaging and calling platform supporting private chats, group conversations, voice and video calls, stickers, communities, and business communication."),
("Clubhouse","Clubhouse is an audio-social platform built around live conversations in rooms. Users can listen to or participate in discussions organized around topics and communities."),
("Flickr","Flickr is an image and video hosting community used for photo sharing, organization, discovery, and photography-focused social interaction."),
("Behance","Behance is a creative portfolio and discovery platform associated with Adobe. Designers, photographers, illustrators, and other creatives showcase projects and connect with audiences."),
("Dribbble","Dribbble is a design community and portfolio platform where designers share work, discover inspiration, and find professional opportunities."),
("Goodreads","Goodreads is a social platform for readers where users track books, write reviews, rate books, create shelves, and follow other readers and authors."),
("Letterboxd","Letterboxd is a social platform for film enthusiasts where users log films, rate and review movies, create lists, follow people, and discuss cinema."),
("Strava","Strava is a social fitness platform for recording and sharing activities such as running and cycling. It provides activity feeds, clubs, challenges, routes, and performance analysis."),
("GitHub","GitHub is a developer platform that also provides social collaboration features through profiles, repositories, followers, discussions, issues, pull requests, and contribution activity."),
("Stack Overflow","Stack Overflow is a question-and-answer community focused on programming and software development. Users ask technical questions, provide answers, vote on content, and build reputation."),
("Patreon","Patreon is a membership platform that allows creators to provide exclusive content and benefits to supporters in exchange for recurring payments."),
("OnlyFans","OnlyFans is a subscription-based creator platform where creators can offer content and interactions to paying subscribers. Its use cases vary by creator and may include entertainment, fitness, education, and other content."),
# Concepts
("Social Media","Social media refers to internet-based services that allow people and organizations to create, publish, share, discuss, and interact with content and communities."),
("Social Networking","Social networking is the use of online platforms to create relationships, professional connections, communities, and ongoing communication between users."),
("Social Media Platform","A social media platform is a digital service that facilitates user-generated content, interaction, networking, discovery, communication, or community participation."),
("Social Media Profile","A social media profile represents a user, creator, organization, or brand on a platform. It commonly contains a name, username, biography, profile image, links, and published activity."),
("Social Media Feed","A social media feed is a continuously updated stream of content selected from accounts, communities, topics, or recommendations. Platforms may rank feed items using signals such as relevance, engagement, freshness, and user preferences."),
("Social Media Algorithm","A social media algorithm is a computational system used to rank, recommend, filter, or personalize content. Ranking systems may use signals related to user interests, interactions, content characteristics, and freshness."),
("Content Recommendation","Content recommendation systems suggest posts, videos, accounts, products, or communities that a platform predicts a user may find useful or interesting."),
("Social Graph","A social graph represents relationships between users, accounts, communities, and other entities. It can model followers, friends, subscriptions, memberships, and interactions."),
("Follower","A follower is a user who subscribes to updates from another account on a social platform. Different platforms use different models for following, subscribing, or connecting."),
("Following","Following is the action of subscribing to another account's content or updates. Following relationships can influence a user's feed and discovery experience."),
("Friend Request","A friend request is an invitation to establish a social connection on a platform where relationships may require mutual acceptance."),
("Like","A like is an interaction used to express positive feedback or interest in social media content. Like counts may influence ranking and analytics depending on the platform."),
("Reaction","A reaction is an expressive interaction attached to content or messages, such as liking, loving, laughing, showing surprise, or expressing sadness."),
("Comment","A comment is a user-generated response attached to a social media post, video, image, or discussion. Comments can create threaded conversations."),
("Share","Sharing is the act of distributing social media content to another audience, profile, conversation, community, or external destination."),
("Repost","A repost republishes or redistributes another user's content to the reposting user's audience, depending on platform terminology and rules."),
("Retweet","Retweet was Twitter's historical term for redistributing another user's post to followers. X uses repost terminology in its current interface."),
("Hashtag","A hashtag is a word or phrase preceded by a hash symbol and used to classify or discover related social media content."),
("Mention","A mention identifies another account in a social media post or comment, often using a username or account handle."),
("Tagging","Tagging associates an account or entity with content such as a photo, video, or post. Tagging can notify the associated account depending on platform settings."),
("Social Media Story","A social media Story is a temporary content format commonly presented in a sequence of photos or videos and traditionally designed to disappear after a limited period."),
("Short Form Video","Short-form video is a concise video format designed for quick viewing and mobile discovery. Platforms such as TikTok, Instagram, YouTube, and Snapchat emphasize this format."),
("Live Streaming","Live streaming transmits audio or video content to an audience in real time. Social platforms use live streams for gaming, events, education, entertainment, shopping, and conversations."),
("Social Audio","Social audio refers to social interaction centered on live or recorded voice conversations. Audio rooms allow audiences to listen and sometimes participate in discussions."),
("Direct Message","A direct message is a private communication between users on a social platform. DMs may support text, media, voice messages, links, and other content."),
("Group Chat","A group chat is a private conversation involving multiple participants. Social and messaging platforms commonly provide group administration, permissions, media sharing, and notifications."),
("Online Community","An online community is a group of people interacting around a shared interest, identity, profession, activity, or goal through digital communication tools."),
("Creator Economy","The creator economy is an ecosystem in which individuals produce content or digital products and earn income through advertising, subscriptions, sponsorships, memberships, commerce, or other monetization models."),
("Content Creator","A content creator produces digital material such as videos, images, articles, podcasts, live streams, tutorials, or social posts for an audience."),
("Influencer","A social media influencer is a creator or public personality whose online presence can affect audience opinions, attention, or purchasing behavior."),
("Micro Influencer","A micro-influencer is generally a creator with a smaller but potentially highly engaged audience in a specific niche. Brands may work with micro-influencers for targeted campaigns."),
("Nano Influencer","A nano-influencer typically has a very small social following and may have strong community-level engagement and authenticity in a narrow niche."),
("Brand Account","A brand account represents a business, organization, product, or service on a social platform and is typically used for communication, marketing, customer support, and community building."),
("Social Media Marketing","Social media marketing uses social platforms to promote products, services, organizations, or ideas through organic content, paid advertising, partnerships, and community engagement."),
("Social Media Advertising","Social media advertising is paid promotion delivered through social platforms. Advertisers can often target audiences using demographic, interest, behavioral, contextual, or first-party signals."),
("Social Media Campaign","A social media campaign is a coordinated set of posts, advertisements, creator partnerships, or activities designed to achieve a specific marketing or communication goal."),
("Social Media Analytics","Social media analytics involves measuring and interpreting platform activity such as reach, impressions, engagement, followers, views, clicks, conversions, and audience characteristics."),
("Engagement Rate","Engagement rate measures interactions relative to an audience or exposure metric. Depending on the methodology, engagement can include likes, comments, shares, saves, clicks, or other actions."),
("Reach","Reach is the number of unique users who are exposed to content or an advertisement during a defined period."),
("Impressions","Impressions count the number of times content or an advertisement is displayed. One user can generate multiple impressions."),
("Views","A view is a platform-defined measure of video or content consumption. The exact conditions required to count a view differ between platforms."),
("Click Through Rate","Click-through rate measures the percentage of impressions that result in clicks. It is commonly calculated as clicks divided by impressions and is used in digital advertising analysis."),
("Conversion Rate","Conversion rate measures the proportion of users who complete a desired action after an interaction, such as making a purchase, signing up, or submitting a form."),
("Social Media ROI","Social media return on investment compares business value generated by social media activity with the costs required to produce and promote that activity."),
("Viral Content","Viral content spreads rapidly through sharing and recommendation and reaches an audience far beyond the creator's initial followers. Virality depends on content, audience behavior, platform distribution, timing, and context."),
("User Generated Content","User-generated content is content created and published by users rather than by the platform or brand itself. Reviews, photos, videos, posts, and testimonials can be examples."),
("UGC Marketing","UGC marketing uses content created by customers or community members to promote a product, service, or brand."),
("Social Commerce","Social commerce combines social interaction and shopping by allowing users to discover, evaluate, and sometimes purchase products through social platforms."),
("Affiliate Marketing","Affiliate marketing is a performance-based marketing model in which partners promote products or services and receive compensation for qualifying actions such as sales or leads."),
("Sponsored Content","Sponsored content is content created or distributed as part of a paid partnership between a creator or publisher and a brand or organization."),
("Influencer Marketing","Influencer marketing uses creators or public personalities to communicate products, services, or ideas to their audiences. Campaigns may be paid, gifted, affiliate-based, or structured around longer partnerships."),
("Community Management","Community management involves building relationships with an online audience, responding to questions, moderating discussions, resolving issues, and encouraging constructive participation."),
("Social Listening","Social listening is the process of monitoring online conversations to understand opinions, trends, customer feedback, brand mentions, and emerging issues."),
("Social Media Monitoring","Social media monitoring tracks mentions, comments, messages, posts, and other activity relevant to a brand, topic, person, or organization."),
("Sentiment Analysis","Sentiment analysis uses natural language processing to estimate whether text expresses positive, negative, neutral, or more detailed emotional attitudes."),
("Social Media Scheduling","Social media scheduling allows users or organizations to prepare content in advance and publish it at planned times across one or more platforms."),
("Social Media Management Tool","Social media management tools help organizations plan, publish, monitor, analyze, and sometimes respond to activity across multiple social platforms."),
("Social Media API","A social media API provides programmatic access to platform features and data according to the platform's authentication, permissions, rate limits, and developer policies."),
("OAuth","OAuth is an authorization framework that allows an application to obtain limited access to resources on behalf of a user without requiring the application to know the user's password."),
("Social Login","Social login lets users authenticate to an application using an identity provider account, often through OAuth or OpenID Connect."),
("OpenID Connect","OpenID Connect is an identity layer built on OAuth 2.0 that enables applications to verify a user's identity and obtain standardized identity information."),
("ActivityPub","ActivityPub is an open decentralized social networking protocol standardized by the W3C. It supports federation between independently operated servers and enables users on compatible services to interact."),
("Federated Social Network","A federated social network consists of independently operated servers that communicate through a shared protocol. Users can interact across servers without a single central service controlling every community."),
("Algorithmic Feed","An algorithmic feed ranks content using software rather than displaying items solely in chronological order. Ranking may personalize content to each user."),
("Chronological Feed","A chronological feed primarily orders posts by time, often showing newer content before older content. Some platforms provide chronological views alongside recommendation-based feeds."),
("Content Moderation","Content moderation involves reviewing, filtering, labeling, removing, or restricting content according to platform rules and applicable policies."),
("Community Guidelines","Community guidelines describe rules for acceptable behavior and content on a social platform or community."),
("Account Verification","Account verification is a process used to establish that an account represents a particular person, organization, or entity. Verification systems and requirements differ across platforms."),
("Blue Check","A blue check is a visual account-status indicator used by some social platforms. Its meaning and eligibility rules have changed over time and differ between services."),
("Privacy Settings","Privacy settings allow users to control aspects of account visibility, communication, activity sharing, personalization, and data access."),
("Blocked User","Blocking prevents or limits interaction between accounts. The exact behavior can include restricting messages, comments, profile visibility, mentions, or other interactions."),
("Muted User","Muting hides or reduces another account's content or notifications without necessarily notifying the muted account or ending a follow relationship."),
("Restricted Account","Account restriction is a moderation or privacy feature that limits interactions with another user without using a full block. Exact behavior depends on the platform."),
("Two Factor Authentication","Two-factor authentication adds an additional verification step beyond a password. Common second factors include authenticator applications, security keys, and one-time codes."),
("End To End Encryption","End-to-end encryption protects message content so that only communicating endpoints are intended to access the plaintext. Some messaging platforms apply it by default while others use it for specific conversations."),
("Social Media Safety","Social media safety includes practices for protecting accounts, personal information, devices, and users from scams, harassment, malicious links, impersonation, and unauthorized access."),
("Online Harassment","Online harassment involves repeated or harmful unwanted behavior through digital platforms. Responses can include blocking, reporting, moderation, privacy controls, and support from trusted people or organizations."),
("Cyberbullying","Cyberbullying is bullying carried out using digital technologies such as social media, messaging services, online communities, or gaming platforms."),
("Social Engineering","Social engineering manipulates people into revealing information, granting access, or performing actions that compromise security. Phishing and impersonation are common examples."),
("Social Media Scam","A social media scam uses deceptive posts, messages, profiles, advertisements, or offers to obtain money, credentials, personal information, or other benefits fraudulently."),
("Fake Account","A fake account is an account that misrepresents its identity or purpose. Fake accounts can be used for spam, impersonation, fraud, manipulation, or other abusive activities."),
("Bot Account","A bot account is an account operated partly or fully by software. Bots can provide useful automation, but malicious bots can generate spam, manipulate discussions, scrape data, or amplify content."),
("Social Media Bot","A social media bot is software that automatically performs actions such as posting, responding, following, collecting information, or moderating content on a social platform."),
("Social Media Spam","Social media spam consists of unwanted repetitive or promotional content, messages, comments, or accounts. Platforms use automated detection and moderation to reduce spam."),
("Shadow Banning","Shadow banning is an informal term for reducing the visibility or distribution of an account or content without clearly notifying the user. Platform-specific moderation and recommendation behavior should not automatically be interpreted as shadow banning."),
("Content Ranking","Content ranking determines the order in which posts, videos, search results, recommendations, or comments are presented to users."),
("Search on Social Media","Social media search helps users discover accounts, posts, hashtags, videos, communities, topics, and other content. Search systems may combine text relevance with popularity, freshness, personalization, and safety signals."),
("Trending Topic","A trending topic is a subject receiving unusually high levels of attention or discussion on a platform during a particular period."),
("Social Media Hashtag Campaign","A hashtag campaign encourages people to publish or discover content under a shared hashtag to increase awareness, participation, or discoverability."),
("Social Media Branding","Social media branding is the process of maintaining a consistent identity across profiles, visuals, tone, messaging, and community interactions."),
("Personal Branding","Personal branding is the deliberate development and communication of a person's professional or public identity across online and offline channels."),
("Creator Monetization","Creator monetization includes methods through which creators generate income, including advertising revenue, subscriptions, sponsorships, memberships, donations, affiliate links, digital products, and merchandise."),
("Ad Revenue Sharing","Ad revenue sharing is a monetization model in which a platform distributes part of advertising revenue associated with eligible creator content according to its program rules."),
("Channel Membership","Channel membership is a recurring support model in which users pay a creator or channel for access to additional benefits, content, badges, or community features."),
("Subscription Model","A social subscription model charges users recurring fees for access to premium content, features, communities, or creator benefits."),
("Donation","A donation allows an audience member to provide voluntary financial support to a creator, organization, or community."),
("Live Stream Donation","Live stream donations are financial contributions made by viewers during live broadcasts. Platforms may provide built-in donation, gifting, or tipping mechanisms."),
("Virtual Gift","A virtual gift is a digital item purchased or awarded on some social platforms and sent to creators or users during interactions, particularly live streams."),
("Social Media Creator Fund","A creator fund is a platform-operated program intended to financially support eligible creators based on activity or content. Program structures and eligibility can change."),
("Social Media Verification","Social media verification refers to processes or programs used to authenticate accounts, signal identity, or provide account features associated with verified status."),
("Social Media Moderation","Social media moderation applies platform rules to user-generated content and behavior. It can involve automated systems, human reviewers, user reports, and appeals."),
("Content Report","A content report is a user submission notifying a platform about potentially harmful, prohibited, misleading, or otherwise problematic content or behavior."),
("Appeal Process","An appeal process allows users to request review of certain moderation or account decisions. The exact process differs across platforms."),
("Digital Wellbeing","Digital wellbeing refers to managing technology use in ways that support healthy routines, attention, relationships, privacy, and overall quality of life."),
("Screen Time","Screen time measures or estimates time spent using digital devices or applications. Many operating systems provide tools for reviewing and managing usage."),
("Social Media Addiction","Problematic social media use describes patterns of use that interfere with daily functioning, responsibilities, sleep, relationships, or wellbeing. It is useful to distinguish heavy use from clinically recognized disorders."),
("Social Media Detox","A social media detox is a voluntary period of reducing or stopping social media use to reassess habits, attention, and wellbeing."),
("Digital Footprint","A digital footprint is the collection of information and traces associated with a person's online activities, including posts, interactions, accounts, and publicly available data."),
("Online Identity","Online identity is the collection of profiles, usernames, content, relationships, and representations through which a person or organization appears on the internet."),
("Social Media Data","Social media data can include posts, comments, reactions, follower relationships, timestamps, engagement events, profile information, and other platform-generated records, subject to platform policies and privacy controls."),
("Social Media Analytics Dashboard","A social media analytics dashboard presents metrics such as reach, impressions, engagement, audience growth, views, clicks, and conversions in a centralized interface."),
("Social Media KPI","Social media key performance indicators are measurable values used to evaluate social activity against objectives, such as engagement rate, reach, follower growth, click-through rate, leads, or conversions."),
("Audience Demographics","Audience demographics describe characteristics of an audience, which can include age ranges, locations, languages, interests, or other aggregated attributes depending on platform analytics."),
("Organic Reach","Organic reach is exposure achieved without directly paying for advertising placement. It can result from followers, sharing, search, recommendations, and other platform distribution."),
("Paid Reach","Paid reach is exposure generated through paid advertising or promoted distribution."),
("Engagement","Social media engagement refers to interactions between users and content, such as likes, comments, shares, saves, clicks, follows, messages, or other platform-defined actions."),
("Social Media Funnel","A social media marketing funnel describes stages through which an audience can move from awareness to consideration, engagement, conversion, and retention."),
("Social Media Content Strategy","A social media content strategy defines goals, target audiences, content themes, formats, publishing practices, community approaches, and measurement methods for social channels."),
("Content Calendar","A social media content calendar organizes planned posts, campaigns, events, formats, platforms, publishing dates, and responsible team members."),
("Social Media Copywriting","Social media copywriting is the creation of concise text designed for social posts, captions, advertisements, calls to action, and community interactions."),
("Social Media SEO","Social media SEO refers to optimizing profiles and content so they are easier to discover through platform search and external search engines. It can involve keywords, descriptions, titles, captions, hashtags, and accessible content."),
("Social Search","Social search is discovery through social platform search systems, including searches for people, posts, videos, products, hashtags, places, or topics."),
("Social Media Accessibility","Social media accessibility involves making content usable by people with disabilities. Practices include captions, alt text, readable typography, sufficient contrast, descriptive links, and accessible video/audio."),
("Alt Text","Alt text is a textual description of an image intended to communicate relevant visual information to people who cannot see the image. Social platforms may provide fields for adding alternative text."),
("Video Captions","Video captions display spoken dialogue and relevant audio information as text. Captions improve accessibility and can help users understand videos when audio is unavailable."),
("Social Media Crisis Management","Social media crisis management involves monitoring rapidly developing issues, coordinating responses, communicating accurately, correcting misinformation, and protecting audiences and organizational reputation."),
("Reputation Management","Online reputation management involves monitoring and responding to information and perceptions about a person, brand, or organization across digital channels."),
("Social Media Policy","A social media policy defines acceptable organizational use of social platforms, security expectations, disclosure requirements, brand guidelines, and response procedures."),
("Employee Advocacy","Employee advocacy encourages employees to share approved organizational content or communicate about their workplace through personal professional networks."),
("Social Selling","Social selling uses social networks to identify prospects, build relationships, share useful information, and support sales conversations."),
("Social Customer Service","Social customer service provides support through social posts, comments, direct messages, and other platform communication channels."),
("Social Media Listening Tool","A social media listening tool collects and analyzes public or authorized social conversations to identify mentions, trends, sentiment, and emerging topics."),
("Social Media Benchmarking","Social media benchmarking compares performance against previous periods, competitors, industry standards, or defined targets."),
("A/B Testing Social Media","A/B testing compares different versions of social content or advertising variables to determine which performs better under a defined measurement method."),
("Social Media Experiment","A social media experiment is a controlled or structured test of content, audience, timing, creative, messaging, or distribution designed to learn what affects performance."),
("Creator Collaboration","Creator collaboration is a partnership in which two or more creators or organizations jointly produce or promote content."),
("Cross Posting","Cross-posting means publishing related or identical content across multiple social platforms, often with adjustments for each platform's audience and format."),
("Omnichannel Social Strategy","An omnichannel social strategy coordinates communication across multiple platforms while adapting content and interactions to each channel."),
("Social Media Integration","Social media integration connects social platform capabilities with websites, applications, analytics systems, customer support tools, or marketing systems."),
("Social Media Webhook","A social media webhook is a mechanism through which an external system can receive event notifications from a platform or service when supported by its API."),
("Social Media Data API","A social media data API provides structured programmatic access to selected platform data subject to authentication, permissions, rate limits, privacy rules, and developer policies."),
("Rate Limit","A rate limit restricts how many API requests an application can make during a period. Platforms use rate limits to protect infrastructure and manage fair access."),
("API Access Token","An API access token is a credential used by an application to access authorized resources through an API. Tokens should be stored securely and granted only necessary permissions."),
("Social Media Database","A social media database can store structured records representing users, posts, comments, reactions, relationships, hashtags, media metadata, and analytics for an authorized application or dataset."),
("Social Media Search Engine","A social media search engine indexes or queries social content to help users find posts, accounts, topics, communities, videos, and discussions."),
("Social Media Recommendation Engine","A recommendation engine predicts content or accounts that a user may find relevant based on signals such as interactions, interests, content similarity, and context."),
("Engagement Prediction","Engagement prediction uses statistical or machine learning models to estimate how likely users are to interact with content."),
("Social Network Analysis","Social network analysis studies relationships and interactions represented as graphs. It can identify communities, central nodes, connection patterns, and information flow."),
("Community Detection","Community detection identifies groups of closely connected nodes in a network. Algorithms can help analyze social communities, communication networks, and recommendation systems."),
("Influence Measurement","Influence measurement estimates the ability of an account or entity to affect attention, engagement, behavior, or information diffusion within a network."),
("Information Diffusion","Information diffusion describes how content, ideas, or information spread through a network of connected users."),
("Misinformation","Misinformation is false or inaccurate information shared without necessarily intending to deceive. Social platforms may use labels, fact-checking, reduced distribution, or other interventions."),
("Disinformation","Disinformation is deliberately false or misleading information created or distributed with an intent to deceive or manipulate."),
("Content Authenticity","Content authenticity concerns whether digital content accurately represents its claimed source, context, origin, or creation process."),
("Deepfake","A deepfake is synthetic or manipulated media generated or modified using machine learning to depict people or events in ways that may be misleading."),
("Synthetic Media","Synthetic media is digitally generated or substantially altered media, including AI-generated images, audio, video, or text."),
("Platform Interoperability","Platform interoperability allows different systems or services to exchange data or communicate using compatible standards or APIs."),
("Data Portability","Data portability is the ability to move or transfer personal or user-generated data from one service or system to another, subject to technical and legal constraints."),
("Platform Lock In","Platform lock-in occurs when users or organizations become dependent on a particular platform because moving data, audiences, workflows, or functionality elsewhere is difficult."),
("Social Media Ecosystem","The social media ecosystem includes platforms, users, creators, advertisers, developers, agencies, communities, content, recommendation systems, and supporting technology."),
("Social Media Trends","Social media trends are patterns of rapidly increasing attention, behavior, formats, topics, memes, or creator practices on social platforms."),
("Meme","A meme is a cultural idea, joke, image, phrase, or format that spreads and is adapted by people, especially through internet communities and social media."),
("Internet Meme Culture","Internet meme culture consists of shared humorous or cultural formats that communities remix, reinterpret, and distribute online."),
("Hashtag Trend","A hashtag trend occurs when a hashtag experiences unusually high usage or attention during a particular period."),
("Social Media News","Social media news refers to news and current events discovered, discussed, distributed, or commented on through social platforms."),
("Citizen Journalism","Citizen journalism refers to reporting or documenting events by members of the public rather than exclusively by professional journalists. Social platforms can enable rapid distribution of eyewitness material."),
("Social Media Journalism","Social media journalism uses social platforms for reporting, discovery, audience interaction, live updates, distribution, and multimedia storytelling."),
("Podcast Social Promotion","Podcast social promotion uses social posts, short clips, community engagement, and creator collaborations to increase awareness and listenership for podcasts."),
("Social Media Video Marketing","Social media video marketing uses short or long video content to build awareness, engagement, leads, sales, or community across social platforms."),
("Shorts","YouTube Shorts is YouTube's short-form vertical video format designed for mobile viewing and discovery."),
("Reels","Instagram Reels is a short-form video format on Instagram designed for creating, editing, discovering, and sharing vertical video content."),
("Stories","Instagram Stories are temporary photo and video posts that traditionally disappear after a limited period and support interactive elements such as stickers, polls, questions, and links."),
("YouTube Channel","A YouTube channel is a creator or organization page where videos, Shorts, playlists, live streams, and other channel information are organized."),
("Instagram Creator","An Instagram creator is a user who publishes content and builds an audience on Instagram, often using professional tools, analytics, brand collaborations, and monetization features where eligible."),
("LinkedIn Company Page","A LinkedIn Company Page represents an organization and can be used to publish updates, showcase company information, share jobs, and engage with a professional audience."),
("Reddit Subreddit","A subreddit is a topic-focused community within Reddit with its own rules, moderators, posts, comments, and membership."),
("Discord Server","A Discord server is a community space containing channels, roles, permissions, and members. Servers can be organized around gaming, education, technology, creators, or other interests."),
("Telegram Channel","A Telegram channel is a broadcast-oriented space where administrators can publish messages to a potentially large audience."),
("WhatsApp Community","A WhatsApp Community organizes related groups under a common structure and can provide announcements and community-level organization."),
]

OFFICIAL_URLS = {
    # Platforms
    "Facebook": "https://www.facebook.com",
    "Instagram": "https://www.instagram.com",
    "YouTube": "https://www.youtube.com",
    "WhatsApp": "https://www.whatsapp.com",
    "Messenger": "https://www.messenger.com",
    "TikTok": "https://www.tiktok.com",
    "X": "https://x.com",
    "LinkedIn": "https://www.linkedin.com",
    "Reddit": "https://www.reddit.com",
    "Pinterest": "https://www.pinterest.com",
    "Snapchat": "https://www.snapchat.com",
    "Telegram": "https://telegram.org",
    "Discord": "https://discord.com",
    "Threads": "https://www.threads.net",
    "Twitch": "https://www.twitch.tv",
    "Mastodon": "https://joinmastodon.org",
    "Bluesky": "https://bsky.app",
    "Tumblr": "https://www.tumblr.com",
    "Quora": "https://www.quora.com",
    "Medium": "https://medium.com",
    "WeChat": "https://www.wechat.com",
    "Weibo": "https://weibo.com",
    "VK": "https://vk.com",
    "LINE": "https://line.me",
    "KakaoTalk": "https://www.kakaocorp.com",
    "Signal": "https://signal.org",
    "Skype": "https://www.skype.com",
    "Viber": "https://www.viber.com",
    "Clubhouse": "https://www.clubhouse.com",
    "Flickr": "https://www.flickr.com",
    "Behance": "https://www.behance.net",
    "Dribbble": "https://dribbble.com",
    "Goodreads": "https://www.goodreads.com",
    "Letterboxd": "https://letterboxd.com",
    "Strava": "https://www.strava.com",
    "GitHub": "https://github.com",
    "Stack Overflow": "https://stackoverflow.com",
    "Patreon": "https://www.patreon.com",
    "OnlyFans": "https://onlyfans.com",

    # Features & Specific Topics
    "Shorts": "https://www.youtube.com/shorts",
    "Reels": "https://www.instagram.com/reels",
    "Stories": "https://www.instagram.com",
    "YouTube Channel": "https://www.youtube.com",
    "Instagram Creator": "https://creators.instagram.com",
    "LinkedIn Company Page": "https://www.linkedin.com/business/marketing/pages",
    "Reddit Subreddit": "https://www.reddit.com",
    "Discord Server": "https://discord.com",
    "Telegram Channel": "https://telegram.org",
    "WhatsApp Community": "https://www.whatsapp.com",

    # Protocols & Standards
    "OAuth": "https://oauth.net",
    "OpenID Connect": "https://openid.net/connect/",
    "ActivityPub": "https://www.w3.org/TR/activitypub/",
}

def get_official_url(title):
    if title in OFFICIAL_URLS:
        return OFFICIAL_URLS[title]
    t_lower = title.lower()
    if "instagram" in t_lower:
        return "https://www.instagram.com"
    elif "youtube" in t_lower:
        return "https://www.youtube.com"
    elif "facebook" in t_lower:
        return "https://www.facebook.com"
    elif "linkedin" in t_lower:
        return "https://www.linkedin.com"
    elif "twitter" in t_lower or "x " in t_lower:
        return "https://x.com"
    elif "reddit" in t_lower:
        return "https://www.reddit.com"
    elif "tiktok" in t_lower:
        return "https://www.tiktok.com"
    elif "api" in t_lower or "developer" in t_lower:
        return "https://developer.meta.com"
    elif "creator" in t_lower or "influencer" in t_lower or "monetization" in t_lower:
        return "https://creators.instagram.com"
    elif "marketing" in t_lower or "advertising" in t_lower:
        return "https://www.facebook.com/business"
    else:
        slug = re.sub(r"[^A-Za-z0-9]+", "-", title.lower()).strip("-")
        return f"https://www.facebook.com/business/learn/topics/{slug}"

# Build the same simple Document records.
records = []
for i, (title, content) in enumerate(social):
    records.append({
        "title": title,
        "content": content,
        "description": content.split(".")[0] + ".",
        "url": get_official_url(title),
    })

# Make a dedicated seeder rather than modifying the previous general seed.
lines = [
'import prisma from "../config/prisma.config.js";',
"",
"/**",
" * VedEngine Social Media Knowledge Database Seeder",
f" * Total curated entries: {len(records)}",
" * Uses the same Document schema as the original seed.",
" */",
"",
"const SOCIAL_MEDIA_DATA = [",
]
for r in records:
    def js(s):
        return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ") + '"'
    lines += [
        "    {",
        f"        title: {js(r['title'])},",
        f"        content: {js(r['content'])},",
        f"        description: {js(r['description'])},",
        f"        url: {js(r['url'])},",
        "        fileType: 'WEB',",
        "    },",
    ]
lines += [
"];",
"",
"async function seedSocialMediaData() {",
"    console.log('\\n╔══════════════════════════════════════════════════════════════╗');",
"    console.log('║        VedEngine Social Media Database Seeder              ║');",
"    console.log('╚══════════════════════════════════════════════════════════════╝');",
"",
"    let inserted = 0;",
"    let updated = 0;",
"    let failed = 0;",
"",
"    for (const entry of SOCIAL_MEDIA_DATA) {",
"        try {",
"            const existing = await prisma.document.findFirst({",
"                where: { title: entry.title },",
"                select: { id: true, url: true },",
"            });",
"",
"            if (existing) {",
"                await prisma.document.update({",
"                    where: { id: existing.id },",
"                    data: { url: entry.url },",
"                });",
"                console.log(`  🔄 Updated URL: ${entry.title} -> ${entry.url}`);",
"                updated++;",
"                continue;",
"            }",
"",
"            await prisma.document.create({",
"                data: {",
"                    title: entry.title,",
"                    content: entry.content,",
"                    description: entry.description,",
"                    url: entry.url,",
"                    fileType: 'WEB',",
"                },",
"            });",
"",
"            console.log(`  ✅ Indexed: ${entry.title}`);",
"            inserted++;",
"        } catch (error) {",
"            console.error(`  ❌ Failed: ${entry.title} - ${error.message}`);",
"            failed++;",
"        }",
"    }",
"",
"    console.log('\\n╔══════════════════════════════════════════════════════════════╗');",
"    console.log('║                    SEEDING COMPLETE                         ║');",
"    console.log('╚══════════════════════════════════════════════════════════════╝');",
"    console.log(`\\n📊 Results:`);",
"    console.log(`   ✅ Inserted:  ${inserted}`);",
"    console.log(`   🔄 Updated:   ${updated}`);",
"    console.log(`   ❌ Failed:    ${failed}`);",
"    console.log(`   📦 Total:     ${SOCIAL_MEDIA_DATA.length}`);",
"",
"    await prisma.$disconnect();",
"}",
"",
"seedSocialMediaData().catch((err) => {",
"    console.error('💥 Seeder crashed:', err);",
"    prisma.$disconnect();",
"    process.exit(1);",
"});",
]
out = Path(__file__).parent / "seed_social_media.js"
out.write_text("\n".join(lines), encoding="utf-8")
print(f"Created {out.name} with {len(records)} social-media entries.")
